*

diff --git a/agent-directive/Jenkinsfile-docker b/agent-directive/Jenkinsfile-docker
--- a/agent-directive/Jenkinsfile-docker
+++ b/agent-directive/Jenkinsfile-docker
@@ -1,20 +1,107 @@
 pipeline {
     agent none
 
-    stages{
-        stage("Node Build"){
+    environment {
+        APP_NAME = 'node-app-01'
+        APP_PORT = '3001'
+        APP_VERSION = 'v1'
+    }
+
+    stages {
+
+        stage("Clone") {
+            steps {
+                echo "Cloning the app..."
+
+                git branch: 'Nodejs',
+                    credentialsId: 'github-creds',
+                    url: 'https://github.com/PiyushThaware07/road-to-heaven.git'
+            }
+        }
+
+        stage("Node Build & Lint"){
             agent {
                 docker {
                     image 'node:18'
                 }
             }
-            steps{
+            steps {
+                echo "Running Node.js validation..."
                 sh '''
                     node --version
+                    npm --version
                     npm install
+                    npm run lint || true
                     npm run build
+                    ls -la
                 '''
             }
+        }
+
+        stage("GDI") {
+            steps {
+                echo "Generating the Docker image..."
+
+                sh '''
+                    docker compose build
+                    docker images
+                '''
+            }
+        }
+
+        stage("PDI") {
+            steps {
+                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds',usernameVariable: 'DOCKER_USER',passwordVariable: 'DOCKER_PASS')]) {
+                    echo "Tagging Docker image..."
+                    sh '''
+                        docker tag ${APP_NAME}:${APP_VERSION} ${DOCKER_USER}/${APP_NAME}:${APP_VERSION}
+                        docker images
+                    '''
+
+                    echo "Logging into Docker Hub..."
+                    sh '''
+                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
+                    '''
+
+                    echo "Pushing image..."
+                    sh '''
+                        docker push ${DOCKER_USER}/${APP_NAME}:${APP_VERSION}
+                    '''
+
+                    sh 'docker logout'
+                    echo "Image pushed successfully!"
+                }
+            }
+        }
+
+        stage("RDI") {
+            steps {
+                echo "Running the application..."
+
+                sh '''
+                    docker compose down || true
+                    docker compose up -d
+                '''
+            }
+        }
+    }
+
+    post {
+        success {
+            echo "Pipeline completed successfully."
+        }
+
+        failure {
+            echo "Pipeline failed. Cleaning Docker resources..."
+            sh '''
+                docker compose down || true
+                docker system prune -af --volumes
+            '''
+            echo "Cleanup completed."
+        }
+
+        always {
+            echo "Pipeline execution finished."
         }
     }
 }
